# 3. Log File Formatter
# Objective:
# The aim of this assignment is to format and extract information from raw log files generated by a SaaS application to improve readability and analysis.

# Task 1: Timestamp Extraction
# Write a script that extracts the timestamp from each log entry. Assume that the timestamp is always at the beginning of each line and is enclosed in square brackets (e.g., "[2023-03-15 10:00:00]").

# Task 2: Error Identification
# Create a function that scans through the log file and identifies any error messages. Assume that all error messages start with the word "ERROR:". The function should print out each error message with its corresponding timestamp.

# Task 3: Log Summary
# Develop a script that creates a summary of the log file, including the total number of entries, the number of error messages, and the number of unique timestamps in the file.

def extract_timestamps(log_entries):
    timestamps = [entry.split(']')[0][1:] for entry in log_entries]
    return timestamps

log_entries = [
    "[2023-03-15 10:00:00] INFO: User login successful.",
    "[2023-03-15 10:05:00] ERROR: Failed to connect to database.",
    "[2023-03-15 10:10:00] INFO: Data backup completed successfully."
]

timestamps = extract_timestamps(log_entries)
print("Extracted Timestamps:")
for timestamp in timestamps:
    print(timestamp)


def identify_errors(log_entries):
    for entry in log_entries:
        if "ERROR:" in entry:
            timestamp = entry.split(']')[0][1:]
            error_message = entry.split("ERROR:")[1].strip()
            print(f"{timestamp} - ERROR: {error_message}")

print("\nIdentified Error Messages:")
identify_errors(log_entries)


def log_summary(log_entries):
    total_entries = len(log_entries)
    error_count = sum(1 for entry in log_entries if "ERROR:" in entry)
    unique_timestamps = len(set(extract_timestamps(log_entries)))

    print(f"Log Summary:\nTotal Entries: {total_entries}\nError Messages: {error_count}\nUnique Timestamps: {unique_timestamps}")

print("\nLog File Summary:")
log_summary(log_entries)